import React from 'react';


// List of all countries (ISO 3166-1 alpha-2 codes)
const countries = [
  { code: 'IN', name: 'India', language: 'Hindi' },
  { code: 'US', name: 'United States', language: 'English' },
  { code: 'GB', name: 'United Kingdom', language: 'English' },
  { code: 'CA', name: 'Canada', language: 'English' },
  { code: 'AU', name: 'Australia', language: 'English' },
  { code: 'FR', name: 'France', language: 'French' },
  { code: 'DE', name: 'Germany', language: 'German' },
  { code: 'ES', name: 'Spain', language: 'Spanish' },
  { code: 'IT', name: 'Italy', language: 'Italian' },
  { code: 'RU', name: 'Russia', language: 'Russian' },
  { code: 'CN', name: 'China', language: 'Chinese' },
  { code: 'JP', name: 'Japan', language: 'Japanese' },
  { code: 'KR', name: 'South Korea', language: 'Korean' },
  { code: 'BR', name: 'Brazil', language: 'Portuguese' },
  { code: 'MX', name: 'Mexico', language: 'Spanish' },
  { code: 'ZA', name: 'South Africa', language: 'English' },
  { code: 'SA', name: 'Saudi Arabia', language: 'Arabic' },
  { code: 'TR', name: 'Turkey', language: 'Turkish' },
  { code: 'ID', name: 'Indonesia', language: 'Indonesian' },
  { code: 'PK', name: 'Pakistan', language: 'Urdu' },
  { code: 'BD', name: 'Bangladesh', language: 'Bengali' },
  { code: 'NG', name: 'Nigeria', language: 'English' },
  { code: 'EG', name: 'Egypt', language: 'Arabic' },
  { code: 'AR', name: 'Argentina', language: 'Spanish' },
  { code: 'TH', name: 'Thailand', language: 'Thai' },
  { code: 'VN', name: 'Vietnam', language: 'Vietnamese' },
  { code: 'PH', name: 'Philippines', language: 'Filipino' },
  { code: 'UA', name: 'Ukraine', language: 'Ukrainian' },
  { code: 'PL', name: 'Poland', language: 'Polish' },
  { code: 'IR', name: 'Iran', language: 'Persian' },
  { code: 'IQ', name: 'Iraq', language: 'Arabic' },
  { code: 'NL', name: 'Netherlands', language: 'Dutch' },
  { code: 'SE', name: 'Sweden', language: 'Swedish' },
  { code: 'NO', name: 'Norway', language: 'Norwegian' },
  { code: 'FI', name: 'Finland', language: 'Finnish' },
  { code: 'DK', name: 'Denmark', language: 'Danish' },
  { code: 'BE', name: 'Belgium', language: 'Dutch' },
  { code: 'CH', name: 'Switzerland', language: 'German' },
  { code: 'AT', name: 'Austria', language: 'German' },
  { code: 'GR', name: 'Greece', language: 'Greek' },
  { code: 'IL', name: 'Israel', language: 'Hebrew' },
  { code: 'SG', name: 'Singapore', language: 'English' },
  { code: 'MY', name: 'Malaysia', language: 'Malay' },
  { code: 'NZ', name: 'New Zealand', language: 'English' },
  { code: 'PT', name: 'Portugal', language: 'Portuguese' },
  { code: 'CZ', name: 'Czech Republic', language: 'Czech' },
  { code: 'HU', name: 'Hungary', language: 'Hungarian' },
  { code: 'RO', name: 'Romania', language: 'Romanian' },
  { code: 'SK', name: 'Slovakia', language: 'Slovak' },
  { code: 'BG', name: 'Bulgaria', language: 'Bulgarian' },
  { code: 'HR', name: 'Croatia', language: 'Croatian' },
  { code: 'RS', name: 'Serbia', language: 'Serbian' },
  { code: 'SI', name: 'Slovenia', language: 'Slovene' },
  { code: 'LT', name: 'Lithuania', language: 'Lithuanian' },
  { code: 'LV', name: 'Latvia', language: 'Latvian' },
  { code: 'EE', name: 'Estonia', language: 'Estonian' },
  { code: 'CL', name: 'Chile', language: 'Spanish' },
  { code: 'CO', name: 'Colombia', language: 'Spanish' },
  { code: 'PE', name: 'Peru', language: 'Spanish' },
  { code: 'VE', name: 'Venezuela', language: 'Spanish' },
  { code: 'UY', name: 'Uruguay', language: 'Spanish' },
  { code: 'BO', name: 'Bolivia', language: 'Spanish' },
  { code: 'EC', name: 'Ecuador', language: 'Spanish' },
  { code: 'PY', name: 'Paraguay', language: 'Spanish' },
  { code: 'CR', name: 'Costa Rica', language: 'Spanish' },
  { code: 'PA', name: 'Panama', language: 'Spanish' },
  { code: 'GT', name: 'Guatemala', language: 'Spanish' },
  { code: 'CU', name: 'Cuba', language: 'Spanish' },
  { code: 'DO', name: 'Dominican Republic', language: 'Spanish' },
  { code: 'SV', name: 'El Salvador', language: 'Spanish' },
  { code: 'HN', name: 'Honduras', language: 'Spanish' },
  { code: 'NI', name: 'Nicaragua', language: 'Spanish' },
  { code: 'PR', name: 'Puerto Rico', language: 'Spanish' },
  { code: 'JM', name: 'Jamaica', language: 'English' },
  { code: 'TT', name: 'Trinidad and Tobago', language: 'English' },
  { code: 'BS', name: 'Bahamas', language: 'English' },
  { code: 'BB', name: 'Barbados', language: 'English' },
  { code: 'AG', name: 'Antigua and Barbuda', language: 'English' },
  { code: 'KN', name: 'Saint Kitts and Nevis', language: 'English' },
  { code: 'LC', name: 'Saint Lucia', language: 'English' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', language: 'English' },
  { code: 'GD', name: 'Grenada', language: 'English' },
  { code: 'DM', name: 'Dominica', language: 'English' },
  { code: 'FJ', name: 'Fiji', language: 'English' },
  { code: 'PG', name: 'Papua New Guinea', language: 'English' },
  { code: 'SB', name: 'Solomon Islands', language: 'English' },
  { code: 'VU', name: 'Vanuatu', language: 'English' },
  { code: 'WS', name: 'Samoa', language: 'Samoan' },
  { code: 'TO', name: 'Tonga', language: 'Tongan' },
  { code: 'TV', name: 'Tuvalu', language: 'Tuvaluan' },
  { code: 'KI', name: 'Kiribati', language: 'English' },
  { code: 'NR', name: 'Nauru', language: 'Nauruan' },
  { code: 'MH', name: 'Marshall Islands', language: 'Marshallese' },
  { code: 'FM', name: 'Micronesia', language: 'English' },
  { code: 'PW', name: 'Palau', language: 'Palauan' },
  { code: 'TL', name: 'Timor-Leste', language: 'Tetum' },
  { code: 'MN', name: 'Mongolia', language: 'Mongolian' },
  { code: 'KZ', name: 'Kazakhstan', language: 'Kazakh' },
  { code: 'UZ', name: 'Uzbekistan', language: 'Uzbek' },
  { code: 'TM', name: 'Turkmenistan', language: 'Turkmen' },
  { code: 'KG', name: 'Kyrgyzstan', language: 'Kyrgyz' },
  { code: 'TJ', name: 'Tajikistan', language: 'Tajik' },
  { code: 'AF', name: 'Afghanistan', language: 'Pashto' },
  { code: 'NP', name: 'Nepal', language: 'Nepali' },
  { code: 'LK', name: 'Sri Lanka', language: 'Sinhala' },
  { code: 'MM', name: 'Myanmar', language: 'Burmese' },
  { code: 'KH', name: 'Cambodia', language: 'Khmer' },
  { code: 'LA', name: 'Laos', language: 'Lao' },
  { code: 'MO', name: 'Macau', language: 'Chinese' },
  { code: 'HK', name: 'Hong Kong', language: 'Chinese' },
  { code: 'TW', name: 'Taiwan', language: 'Chinese' },
  { code: 'QA', name: 'Qatar', language: 'Arabic' },
  { code: 'AE', name: 'United Arab Emirates', language: 'Arabic' },
  { code: 'OM', name: 'Oman', language: 'Arabic' },
  { code: 'KW', name: 'Kuwait', language: 'Arabic' },
  { code: 'BH', name: 'Bahrain', language: 'Arabic' },
  { code: 'YE', name: 'Yemen', language: 'Arabic' },
  { code: 'JO', name: 'Jordan', language: 'Arabic' },
  { code: 'LB', name: 'Lebanon', language: 'Arabic' },
  { code: 'SY', name: 'Syria', language: 'Arabic' },
  { code: 'PS', name: 'Palestine', language: 'Arabic' },
  { code: 'MA', name: 'Morocco', language: 'Arabic' },
  { code: 'DZ', name: 'Algeria', language: 'Arabic' },
  { code: 'TN', name: 'Tunisia', language: 'Arabic' },
  { code: 'LY', name: 'Libya', language: 'Arabic' },
  { code: 'SD', name: 'Sudan', language: 'Arabic' },
  { code: 'SS', name: 'South Sudan', language: 'English' },
  { code: 'ET', name: 'Ethiopia', language: 'Amharic' },
  { code: 'KE', name: 'Kenya', language: 'English' },
  { code: 'TZ', name: 'Tanzania', language: 'Swahili' },
  { code: 'UG', name: 'Uganda', language: 'English' },
  { code: 'GH', name: 'Ghana', language: 'English' },
  { code: 'CI', name: 'Ivory Coast', language: 'French' },
  { code: 'SN', name: 'Senegal', language: 'French' },
  { code: 'CM', name: 'Cameroon', language: 'French' },
  { code: 'ZW', name: 'Zimbabwe', language: 'English' },
  { code: 'MZ', name: 'Mozambique', language: 'Portuguese' },
  { code: 'AO', name: 'Angola', language: 'Portuguese' },
  { code: 'MG', name: 'Madagascar', language: 'Malagasy' },
  { code: 'BW', name: 'Botswana', language: 'English' },
  { code: 'NA', name: 'Namibia', language: 'English' },
  { code: 'ZM', name: 'Zambia', language: 'English' },
  { code: 'MW', name: 'Malawi', language: 'English' },
  { code: 'LS', name: 'Lesotho', language: 'English' },
  { code: 'SZ', name: 'Eswatini', language: 'English' },
  { code: 'GA', name: 'Gabon', language: 'French' },
  { code: 'CG', name: 'Congo', language: 'French' },
  { code: 'CD', name: 'Democratic Republic of the Congo', language: 'French' },
  { code: 'GQ', name: 'Equatorial Guinea', language: 'Spanish' },
  { code: 'ST', name: 'Sao Tome and Principe', language: 'Portuguese' },
  { code: 'GW', name: 'Guinea-Bissau', language: 'Portuguese' },
  { code: 'CV', name: 'Cape Verde', language: 'Portuguese' },
  { code: 'SL', name: 'Sierra Leone', language: 'English' },
  { code: 'LR', name: 'Liberia', language: 'English' },
  { code: 'GM', name: 'Gambia', language: 'English' },
  { code: 'MR', name: 'Mauritania', language: 'Arabic' },
  { code: 'DJ', name: 'Djibouti', language: 'French' },
  { code: 'SO', name: 'Somalia', language: 'Somali' },
  { code: 'CF', name: 'Central African Republic', language: 'French' },
  { code: 'NE', name: 'Niger', language: 'French' },
  { code: 'ML', name: 'Mali', language: 'French' },
  { code: 'BF', name: 'Burkina Faso', language: 'French' },
  { code: 'TG', name: 'Togo', language: 'French' },
  { code: 'BJ', name: 'Benin', language: 'French' },
  { code: 'RW', name: 'Rwanda', language: 'Kinyarwanda' },
  { code: 'BI', name: 'Burundi', language: 'Kirundi' },
  { code: 'SZ', name: 'Eswatini', language: 'English' },
  { code: 'SC', name: 'Seychelles', language: 'English' },
  { code: 'MU', name: 'Mauritius', language: 'English' },
  { code: 'KM', name: 'Comoros', language: 'Comorian' },
  { code: 'YT', name: 'Mayotte', language: 'French' },
  { code: 'RE', name: 'Reunion', language: 'French' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', language: 'French' },
  { code: 'GL', name: 'Greenland', language: 'Greenlandic' },
  { code: 'FO', name: 'Faroe Islands', language: 'Faroese' },
  { code: 'IS', name: 'Iceland', language: 'Icelandic' },
  { code: 'MC', name: 'Monaco', language: 'French' },
  { code: 'LI', name: 'Liechtenstein', language: 'German' },
  { code: 'SM', name: 'San Marino', language: 'Italian' },
  { code: 'VA', name: 'Vatican City', language: 'Italian' },
  { code: 'AD', name: 'Andorra', language: 'Catalan' },
  { code: 'LU', name: 'Luxembourg', language: 'Luxembourgish' },
  { code: 'MT', name: 'Malta', language: 'Maltese' },
  { code: 'MC', name: 'Monaco', language: 'French' },
  { code: 'GI', name: 'Gibraltar', language: 'English' },
  { code: 'AX', name: 'Aland Islands', language: 'Swedish' },
  { code: 'GG', name: 'Guernsey', language: 'English' },
  { code: 'JE', name: 'Jersey', language: 'English' },
  { code: 'IM', name: 'Isle of Man', language: 'English' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', language: 'Norwegian' },
  { code: 'BQ', name: 'Caribbean Netherlands', language: 'Dutch' },
  { code: 'CW', name: 'Curacao', language: 'Dutch' },
  { code: 'SX', name: 'Sint Maarten', language: 'Dutch' },
  { code: 'AW', name: 'Aruba', language: 'Dutch' },
  { code: 'MF', name: 'Saint Martin', language: 'French' },
  { code: 'BL', name: 'Saint Barthelemy', language: 'French' },
  { code: 'GP', name: 'Guadeloupe', language: 'French' },
  { code: 'MQ', name: 'Martinique', language: 'French' },
  { code: 'GF', name: 'French Guiana', language: 'French' },
  { code: 'SR', name: 'Suriname', language: 'Dutch' },
  { code: 'PF', name: 'French Polynesia', language: 'French' },
  { code: 'NC', name: 'New Caledonia', language: 'French' },
  { code: 'VU', name: 'Vanuatu', language: 'English' },
  { code: 'SB', name: 'Solomon Islands', language: 'English' },
  { code: 'TO', name: 'Tonga', language: 'Tongan' },
  { code: 'WS', name: 'Samoa', language: 'Samoan' },
  { code: 'KI', name: 'Kiribati', language: 'English' },
  { code: 'NR', name: 'Nauru', language: 'Nauruan' },
  { code: 'TV', name: 'Tuvalu', language: 'Tuvaluan' },
  { code: 'FM', name: 'Micronesia', language: 'English' },
  { code: 'MH', name: 'Marshall Islands', language: 'Marshallese' },
  { code: 'PW', name: 'Palau', language: 'Palauan' },
];

function CountrySelect({ onSelect }) {
  return (
    <div style={{
      width: '100vw',
      height: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(180deg, #00BCD3FF, rgb(69 37 188 / 77%) 100%)',
      color: '#fff',
      flexDirection: 'column',
      fontFamily: 'inherit',
    }}>
      <h2 style={{ marginBottom: 24 }}>Select Your Country</h2>
      <select
        style={{
          padding: '12px 20px',
          borderRadius: '8px',
          fontSize: '18px',
          border: 'none',
          marginBottom: 24,
        }}
        defaultValue=""
        onChange={e => {
          const selected = countries.find(c => c.code === e.target.value);
          if (selected) onSelect(selected);
        }}
      >
        <option value="" disabled>Select country...</option>
        {countries.map(c => (
          <option key={c.code} value={c.code}>{c.name}</option>
        ))}
      </select>
      <div style={{ fontSize: 14, color: '#fff', opacity: 0.7 }}>Language will be set automatically</div>
    </div>
  );
}

export default CountrySelect;
